---
- name: Reload udev rules
  ansible.builtin.command: udevadm control --reload-rules
  notify: Trigger udev

- name: Trigger udev
  ansible.builtin.command: udevadm trigger

- name: Reboot required for UART
  ansible.builtin.file:
    path: /var/run/reboot-required
    state: touch
    mode: "0644"

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart journald
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
