---
- name: Reload udev rules
  ansible.builtin.command: udevadm control --reload-rules
  notify: Trigger udev

- name: Trigger udev
  ansible.builtin.command: udevadm trigger

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Reload NetworkManager connections
  ansible.builtin.command: nmcli connection reload
  changed_when: true
  failed_when: false
