# shellcheck shell=bash
# Regenerate test/fixtures.json. The fingerprints are produced by ssh-keygen, NOT by our own
# code -- the whole point is that the test compares our implementation against OpenSSH's,
# rather than against itself. Run from containers/fleet-control/.
set -euo pipefail
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
ssh-keygen -t ed25519 -N '' -C '' -f "$tmp/ed" -q
ssh-keygen -t rsa -b 2048 -N '' -C '' -f "$tmp/rsa" -q
cat >test/fixtures.json <<JSON
{
  "_comment": "Ground truth generated by ssh-keygen, not by this code. Regenerate with test/gen-fixtures.sh.",
  "ed25519": { "blob": "$(awk '{print $2}' "$tmp/ed.pub")", "fingerprint": "$(ssh-keygen -lf "$tmp/ed.pub" | awk '{print $2}')" },
  "rsa2048": { "blob": "$(awk '{print $2}' "$tmp/rsa.pub")", "fingerprint": "$(ssh-keygen -lf "$tmp/rsa.pub" | awk '{print $2}')" }
}
JSON
